### PR TITLE
Org refactoring

### PR DESCRIPTION
**Pull request by opishcheiko**
- tried to fix some issues with mobile version. Didn't succeed on every page, but it's better than before.

The guys asked us to make an organisation specific pages, so now:
- the homepage will be a page about us and our initiative
Screenshot 2020-12-06 at 15 18 56

- to go to specific org, they will have to go to `/[any-name]` for example homepage for Visible Children `/visible-children`. And their org profile will be `/visible-children/orgProfile`. I just moved all files to [org] folder, that's why there are many files changed. Tbh, not fully sure how it's going to work with the backend, will need to have a look.

- every other page will now be behind log in screen (sponsors, admins, org members)
Screenshot 2020-12-06 at 15 21 14

### CODE REVIEW

**Comment by opishcheiko** [comment]
@Jnegrier any updates on the backend? Would be cool to start making it more alive

**Comment by Jnegrier** [comment]
> @Jnegrier any updates on the backend? Would be cool to start making it more alive

We could say that the foundation for the Core backend is ready, but looks like we would have to rethink the design again, I was actually thinking in create more microservices for each component, like Core to manage organization data, maybe a service just to manage Beneficiary data, another service for Education, other for Wellbeing, we should have a meeting or create a page with ideas to deal with that. Apologies for the delay, will organize something soon.

**Review by Jnegrier — APPROVED** [review]
This look amazing, thanks a million @opishcheiko

**Comment by opishcheiko** [comment]
@Jnegrier maybe you are overthinking a bit? Let's start using what we have maybe and then refactor, if needed?

**Comment by Jnegrier** [comment]
> @Jnegrier maybe you are overthinking a bit? Let's start using what we have maybe and then refactor, if needed?

@opishcheiko mmmmm yeah, I think you're right, we can always refactor at a later stage, will speed up the backend then 👍

**Pull request merged**
