### PR TITLE
Homepage  look

### PR DESCRIPTION
**Pull request by opishcheiko**
- homepage restyle (let's keep it for now and think how to improve)
- backend integration for Admin page: Adding a collaborator - working

### CODE REVIEW

**Comment by opishcheiko** [comment]
@Jnegrier I am thinking about how to style the homepage. 
Please please please, tell me how you see it, this now it's just an idea... (top few elements changed, bottom - the same for now)
I am thinking of what elements do we want to show. Was thinking about the carousel for children, maybe also "Our news" section?

**Comment by Jnegrier** [comment]
> @Jnegrier I am thinking about how to style the homepage.
> Please please please, tell me how you see it, this now it's just an idea... (top few elements changed, bottom - the same for now)
> I am thinking of what elements do we want to show. Was thinking about the carousel for children, maybe also "Our news" section?

@opishcheiko I think it looks amazing, thanks for being so proactive with the new design, I'm not an expert or a person with good taste, but I will think about something and update here later on

**Comment by opishcheiko** [comment]
@Jnegrier can I ask you to run npm build on this PR? it says on my local "failed to compile", but I don't see any visible error. Thanks

**Comment by Jnegrier** [comment]
> @Jnegrier can I ask you to run npm build on this PR? it says on my local "failed to compile", but I don't see any visible error. Thanks

Done, just corrected the issue, it should build fine now 😸

**Review by Jnegrier — APPROVED** [review]
it looks great. So it's just the backend connections, and the homepage will be for later, right?

**Comment by opishcheiko** [comment]
@Jnegrier wow, thanks for fixing, it never showed me where the error is!

The homepage  changes are also there, but it's still more of a draft that a ready piece, I guess we can merge for now and observe, what can be done better. Are you happy with this way, or you think it's better to park the redesign until we decide the way?

**Comment by Jnegrier** [comment]
> @Jnegrier wow, thanks for fixing, it never showed me where the error is!
> 
> The homepage changes are also there, but it's still more of a draft that a ready piece, I guess we can merge for now and observe, what can be done better. Are you happy with this way, or you think it's better to park the redesign until we decide the way?

I'm happy with an iterative way @opishcheiko I will try to help more with a new design for the homepage, so we get something we all like

**Comment by opishcheiko** [comment]
thank you

**Pull request merged**
