### PR TITLE
Spliting media for logo and photo id

### PR DESCRIPTION
**Pull request by Jnegrier**
I had to split media even more, with dedicated pages for logo and photo id, the reason is that it was impossible to create an organization as it was. On the media state, `photo_id` or `logo` were left empty when one of the images was uploaded, so only the last uploaded was set.

### CODE REVIEW

**Comment by opishcheiko** [comment]
really? I saw it working, maybe broke something.
Side thought: we don't really need the logo on the application step, we can kill it and the problem will be solved (not the best, but would make sense)

**Comment by Jnegrier** [comment]
> really? I saw it working, maybe broke something.
> Side thought: we don't really need the logo on the application step, we can kill it and the problem will be solved (not the best, but would make sense)

ok, will remove itlate

**Comment by Jnegrier** [comment]
@opishcheiko at the end, along with removing the logo, I refactored the endpoints using the verified field, so now the creation, updating and reading of the new statuses should work

**Review by opishcheiko — APPROVED** [review]
oo, nce, thanks!

**Pull request merged**
