### PR TITLE
Renaming files + server side rendering for org page

### PR DESCRIPTION
**Pull request by opishcheiko**
- adding a bit of styling of org creation form (padding between fields + some text adjustments for a better ux).
 
Two things:
1. i thought, we shouldn't call it "register organization", more of "apply" or "register your interest". Let me know, what you think.
2. What the hell is "Vision"? Initially we had `mission`, `values`, `your story`, `tagline` fields (or did i have this idea just in my head? 😄  https://mongen-frontend.herokuapp.com/123/orgProfile ). Just thinking as a user, I have organization, what would i write in Vision question, and am kinda lost. I renamed it into "your story" in the form for now, but let's discuss.
____________

 - renaming files not to be camel case to simplify the url look (so createOrg -> create-org, paymentForm -> payment)
 
__________
Started with adding the server rendering for organization (by org id for now):
            -   homepage
            -   about page
  All the other pages will use hardcoded org=1 for now
It's a bit messy still, but hopefully will hook most of the GET pages to the backend

### CODE REVIEW

**Comment by Jnegrier** [comment]
@opishcheiko okay, these are not small changes 🤔 

1. Sounds good to me, it makes sense to rename it, in a way that we communicate that you need to apply for it, and it's not a straightforward process.

2. hahahaha we would have to discuss it, the Vision is the big objective of your organization, normally goes along with the mission, for instance, Mission: "Help people with obesity in Nauru to have healthy lifestyle" and Vision: "Reduce the obesity rate in Nauru to 10% in 2030". So basically, then you direct your work and the efforts of your organization to achieve that vision 👍 I like the other fields you suggest as well, I think that we could add all of them, what do you think?

**Comment by opishcheiko** [comment]
@Jnegrier  never said, it'll be small changes :))
2. okay, now it's more clear. So vision = like the closest milestone they plan to achieve? It's kinda similar to Mission, I guess? Let's call it "Objectives" or something, or we can just explain it better, so the user knows what we are asking.
3. 
Also giving people the option to enter their url... what do you think? Should we maybe automatically convert their name? Or give them the freedom?

**Comment by Jnegrier** [comment]
> @Jnegrier never said, it'll be small changes :))
> 2. okay, now it's more clear. So vision = like the closest milestone they plan to achieve? It's kinda similar to Mission, I guess? Let's call it "Objectives" or something, or we can just explain it better, so the user knows what we are asking.
> 3.
> Also giving people the option to enter their url... what do you think? Should we maybe automatically convert their name? Or give them the freedom?

2. mmmm I really think that Vision is okay, is one of the three basic concepts for management in any organization Mission, Vision and Values. Even if someone has doubts about it, just a quick search will give a good explanation 😄 

3.  Yeah, this is interesting, I think we should provide this liberty, cause it is important for SEO, and generate it could be a headache. I think we need to put good validations tho, I was thinking to use your function `convertTitleToSeoUrl` to automatically suggest a seo_name based on the org name, but also send this seo_name to the backend, and display in the form if it's being used by someone else or not. Also, as I mentioned before, we should protect some names like `admin` or others.

**Comment by opishcheiko** [comment]
okay, let's keep the vision :+1:
What org can be named "admin"? I mean, since every new org will be a pending review one, without a page, I guess we don't need to worry? But also we can put custom validations np.
/admin is working fine out of the box with nextJS, or any page that's created as a file under /pages folder.

**Comment by Jnegrier** [comment]
> okay, let's keep the vision 👍
> What org can be named "admin"? I mean, since every new org will be a pending review one, without a page, I guess we don't need to worry? But also we can put custom validations np.
> /admin is working fine out of the box with nextJS, or any page that's created as a file under /pages folder.

okay, sounds cool 💪

**Review by Jnegrier — APPROVED** [review]
🚀

**Pull request merged**
