### PR TITLE
Added new page to add a organisation

### PR DESCRIPTION
**Pull request by Jnegrier**
Still a work in progress...

- Foundation for the look and feel done

ezgif-7-84cf417d9a71

TODO:
- ~~Generic component with  a select to load countries~~
- ~~Generic component with a select to load collaborator type~~
- POST request to create collaborator
- POST request to create an organization

### CODE REVIEW

**Comment by opishcheiko** [comment]
ii guess this should only be accessible to mongen admins, and this form will be filled by them, right?

**Comment by opishcheiko** [comment]
at least from what James explained, there is an interview process

**Comment by Jnegrier** [comment]
Yeah, I will ask for more details about it, so we modify the model to have all we need, and we define a location for this.

I actually need to update the model for countries, and the current is not correct and we also need to load the countries in some way

**Review by opishcheiko — COMMENTED** [review]
hi Juan, let's maybe merge what's here already, so I can also start looking into some backend integrations?

**Comment by Jnegrier** [comment]
> hi Juan, let's maybe merge what's here already, so I can also start looking into some backend integrations?

Done, I will complete the missing tasks described in this thing in a different PR

**Pull request merged**
